#
# Module manifest for module 'PowerBuild'
#
# Generated by: Pavol Kovalik
#
# Generated on: 2/13/2015
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PowerBuild.dll'

# Version number of this module.
ModuleVersion = '0.1'

# ID used to uniquely identify this module
GUID = 'A828E4B5-B57A-4039-AF11-6D16C3DC9A09'

# Author of this module
Author = 'Pavol Kovalik'

# Company or vendor of this module
# CompanyName = ''

# Copyright statement for this module
Copyright = '(c) 2017 Pavol Kovalik'

# Description of the functionality provided by this module
Description = 'Integrate MSBuild into PowerShell pipeline.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
DotNetFrameworkVersion = '4.6'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @(
    'PowerBuild.dll'
)

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @(
    'PowerBuild.types.ps1xml'
)

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @(
    'PowerBuild.formats.ps1xml'
)

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
# FunctionsToExport = @()

# Cmdlets to export from this module
CmdletsToExport = @(
    'Invoke-MSBuild',
    'New-ConsoleLogger',
    'New-FileLogger',
    'New-Logger',
    'New-StructuredLogger'
)


# Variables to export from this module
# VariablesToExport = '*'

# Aliases to export from this module
# AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('powershell', 'msbuild', 'invoke-msbuild')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/kovalikp/PowerBuild/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/kovalikp/PowerBuild'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    }

}

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
